name: Build LibGDX Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build desktop jar
      run: ./gradlew :lwjgl3:dist

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: KnightAdventure
        path: lwjgl3/build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: KnightAdventure

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.jar"
